# Generated by Django 4.0.6 on 2022-09-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
